apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    ports:
    - containerPort: 80
 initContainers:
  - name: install
    image: busybox
    command:
    - date
  dnsPolicy: Default
